### ISSUE TITLE
Template not respect num of nodes

### ISSUE THREAD

**Issue by keeefin** [stackabletech/t2#36]
I know it is quite cloistered to complain about a 2 node setup but i think there is an issue with selecting the worker node for the history server.

``` 
{
  "apiVersion": "t2.stackable.tech/v1",
  "kind": "Infra",
  "template": "demo-debian-10",
  "metadata": {
    "name": "stackable-demo",
    "description": "This is the cluster I want!"
  },
  "domain": "stackable.demo",
  "sshKeys": [
    "{{t2-ssh-key}}"
  ],
  "spec": {
    "region": "de/fra",
    "nodes": {
      "main": {
        "numberOfNodes": 1,
        "numberOfCores": 2,
        "memoryMb": 1024,
        "diskType": "SSD",
        "diskSizeGb": 15
      },
      "worker": {
        "numberOfNodes": 2,
        "numberOfCores": 2,
        "memoryMb": 1024,
        "diskType": "SSD",
        "diskSizeGb": 15
      }
    }
  },
  "services": {
    "spark-primary": "apiVersion: spark.stackable.tech/v1\nkind: SparkCluster\nmetadata:\n  name: spark-primary\nspec:\n  master:\n    selectors:\n      - nodeName: \"main-1.stackable.demo\"\n        instances: 1\n        masterPort: 9999\n        masterWebUiPort: 11111\n  worker:\n    selectors:\n      - nodeName: \"worker-1.stackable.demo\"\n        instances: 1\n        cores: 1\n        memory: \"1g\"\n  historyServer:\n    selectors:\n      - nodeName: \"worker-3.stackable.demo\"\n        instances: 1\n  version: \"3.0.1\"\n  maxPortRetries: 0\n",
    "spark-secondary": "apiVersion: spark.stackable.tech/v1\nkind: SparkCluster\nmetadata:\n  name: spark-secondary\nspec:\n  master:\n    selectors:\n      - nodeName: \"main-1.stackable.demo\"\n        instances: 1\n        masterPort: 9998\n        masterWebUiPort: 11112\n  worker:\n    selectors:\n      - nodeName: \"worker-2.stackable.demo\"\n        instances: 1\n        cores: 1\n        memory: \"1g\"\n  historyServer:\n    selectors:\n      - nodeName: \"worker-4.stackable.demo\"\n        instances: 1\n  version: \"3.0.1\"\n  maxPortRetries: 0        \n"
  }
}
```

creates following terraform:

```

# service definition files
resource "local_file" "service-spark-primary" {
  filename = "roles/services/files/spark-primary.yaml"
  file_permission = "0440"
  content = <<-END_OF_SERVICE_DEF
apiVersion: spark.stackable.tech/v1
kind: SparkCluster
metadata:
  name: spark-primary
spec:
  master:
    selectors:
      - nodeName: "main-1.stackable.demo"
        instances: 1
        masterPort: 9999
        masterWebUiPort: 11111
  worker:
    selectors:
      - nodeName: "worker-1.stackable.demo"
        instances: 1
        cores: 1
        memory: "1g"
  historyServer:
    selectors:
      - nodeName: "worker-3.stackable.demo"
        instances: 1
  version: "3.0.1"
  maxPortRetries: 0

END_OF_SERVICE_DEF
}

resource "local_file" "service-spark-secondary" {
  filename = "roles/services/files/spark-secondary.yaml"
  file_permission = "0440"
  content = <<-END_OF_SERVICE_DEF
apiVersion: spark.stackable.tech/v1
kind: SparkCluster
metadata:
  name: spark-secondary
spec:
  master:
    selectors:
      - nodeName: "main-1.stackable.demo"
        instances: 1
        masterPort: 9998
        masterWebUiPort: 11112
  worker:
    selectors:
      - nodeName: "worker-2.stackable.demo"
        instances: 1
        cores: 1
        memory: "1g"
  historyServer:
    selectors:
      - nodeName: "worker-4.stackable.demo"
        instances: 1
  version: "3.0.1"
  maxPortRetries: 0        

END_OF_SERVICE_DEF
}
```
